version: '2'

services:
    db:
        build: db
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ajax
    php:
        build: php
        links:
            - db:mysqldb
        volumes:
            - ./www:/var/www/ajax
            - ./logs/ajax:/var/www/ajax/logs
    nginx:
        build: nginx
        ports:
            - 8081:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8082:80
        links:
            - db
